name: vitalsync
description: A new Flutter project.

# Impede a publicação acidental no pub.dev
publish_to: 'none'

# Versão do app: major.minor.patch+build
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  flutter_dotenv: ^5.0.2
  flutter_gemini: ^3.0.0 # integração com Gemini (Google AI)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/cadeado.png
    - assets/coracao.png
    - assets/personicon.png


